version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: minha-vida-dev
    environment:
      POSTGRES_USER: andre
      POSTGRES_PASSWORD: CFi6BiW9rN8q1uj7R0O3
      POSTGRES_DB: minha-vida-dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
